# Generated by Django 4.1 on 2022-09-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="date closed"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="visibilty",
            field=models.BooleanField(default=True, verbose_name="poll visibility"),
        ),
    ]
