# Generated by Django 4.1 on 2022-09-17 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polls", "0002_question_end_date_question_visibilty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="vote_count",
        ),
        migrations.AlterField(
            model_name="question",
            name="end_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="date closed"
            ),
        ),
        migrations.CreateModel(
            name="VoteData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.choice"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
